name: Deploy Frontend

on:
  push:
    branches: [ "main" ] # 监听 main 分支的推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist # 构建后的文件夹
          branch: gh-pages # 部署到 gh-pages 分支
